### ISSUE TITLE
TFO plugin needs a combiner

### ISSUE THREAD

**Issue by irl** [mami-project/pathspider#122]
Add a combine_flows(flows) function to the TFO plugin class, where flows is a tuple in the correct order, that returns an array of conditions.

**Comment by britram** [comment]
Taken from the TMA paper, the conditions here should be as follows:

- `tfo.connectivity.works` (as with ECN, attempt to negotiate TFO does not lead to connectivity failure)
- `tfo.connectivity.broken` (as with ECN, attempt to negotiate TFO leads to connectivity failure, but target is up)
- `tfo.connectivity.offline` (as with ECN, target is down)
- `tfo.cookie.received` (Attempt to get a TFO cookie succeeded)
- `tfo.cookie.not_received` (No TFO cookie available -> TFO not supported)
- `tfo.syndata.acked` (Data on SYN was acked in SYNACK)
- `tfo.syndata.not_acked` (SYNACK acks SYN only)
- `tfo.syndata.broken` (Data on SYN causes connection failure)

Note there is no `tfo.connectivity.transient` because the TFO plugin doesn't try config 1 when config 0 is down, due to timeout issues.
