### ISSUE TITLE
Superfluous client capability updates

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#13]
Why do ControlBatch and ControlWeb call clientpool.update() while waiting for the resolver? The reload of capabilities would seem to be superfluous in this case.

**Comment by gubser** [comment]
In this case, indeed. However, I wanted that resolver.ResolverApi, ecnclient.EcnClient and tbclient.TbClient share a common mplane.client.HttpInitiatorClient object for each vantage point.
The reason for this is to reduce the number of connections because tornado started killing and reopening tcp connections all the time.

Unfortunately, I didn't get around changing the implementation of ecnclient.EcnClient and tbclient.TbClient

**Comment by britram** [comment]
The Tornado issues should be fixable by configuring Tornado's concurrency, no? (In the longer term, Tornado goes away when we replace HTTP with Websockets and move over to asyncio)

**Comment by gubser** [comment]
I think so too. But imo another good reason to do connection pooling is to reduce the polling spam.
 - Also a thing that would go away with websockets, yay!

**Comment by britram** [comment]
Consider just not doing the capability refresh and seeing what happens...

**Comment by gubser** [comment]
not relevant anymore because mplane support was removed.
