### ISSUE TITLE
Redesign flow idle timeout and expiration in the observer

### ISSUE THREAD

**Issue by britram** [mami-project/pathspider#68]
The observer accumulates flows which never see a TCP FIN/RST, including all observed UDP flows. This leads to memory leaks, which can cause excessive memory usage for large jobs. purge_idle() is designed to iterate over all flows in the active table, completing them, but causes timer queue corruption (tick() dies with function > function). 

Consider a minor redesign of how flow expiry works, so that idleness and active shutdown are handled the same.

**Comment by britram** [comment]
#27 and #30 are (probably) deeply related to this bug. Thinking about how to manage flow table growth should be the key goal of the redesign.

**Comment by britram** [comment]
This has been redesigned along the lines of binned idle and expiry times (kind of like it works in QoF):

- Two new data structures, `idle_bins` and `expiry_bins`, keep track of flow IDs based on when they should be marked idle (30 seconds after the last packet, configurable) or expired (5 seconds after a decision to complete them, configurable).
- Arrival of a packet moves its flow into the appropriate idle bin.
- Every n seconds (1, configurable in source), the packet clock advances. when it does, pending idle bins have all their flows completed, and pending expiry bins get emitted.

This appears to work in the `idle_expiring_bintable` branch, doesn't need a timer queue, and seems to have better memory performance than the existing `master` timer queue (and idle-ignoring) code.

**Comment by irl** [comment]
This seems sensible.

I've moved test_observer to the rest of the tests and given it two static PCAP files to test with. It's only validating that the correct number of flows come back currently.

These tests can't run on the Travis CI because python-libtrace is missing there and I haven't had a chance to fix that yet, but they will be skipped and won't just fail. You can still run tests.sh locally and the tests will work.

**Comment by irl** [comment]
Merged
